apiVersion: v1
kind: ServiceAccount
metadata:
  name: daily8-backend-service-account
  labels:
    app.kubernetes.io/name: daily8
    app.kubernetes.io/component: daily8-backend

automountServiceAccountToken: false

imagePullSecrets:
  - name: daily8-image-pull-secret
