apiVersion: v1
kind: Service
metadata:
  name: daily8-backend
  labels:
    app.kubernetes.io/name: daily8
    app.kubernetes.io/component: daily8-backend
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: daily8
    app.kubernetes.io/component: daily8-backend

  ports:
    - name: http
      port: 5010
      targetPort: http
      protocol: TCP
