apiVersion: v1
kind: ConfigMap
metadata:
  name: daily8-client-sub-config
  labels:
    app.kubernetes.io/name: daily8
    app.kubernetes.io/component: daily8-client-sub

data:
  VITE_API_URL: https://daily8-api.richpong.com
