apiVersion: v1
kind: ServiceAccount
metadata:
  name: daily8-client-sub-service-account
  labels:
    app.kubernetes.io/name: daily8
    app.kubernetes.io/component: daily8-client-sub

automountServiceAccountToken: false

imagePullSecrets:
  - name: daily8-image-pull-secret
