apiVersion: v1
kind: Service
metadata:
  name: daily8-client-sub
  labels:
    app.kubernetes.io/name: daily8
    app.kubernetes.io/component: daily8-client-sub

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: daily8
    app.kubernetes.io/component: daily8-client-sub

  ports:
    - name: http
      port: 3008
      targetPort: http
      protocol: TCP
