apiVersion: v1
kind: Secret
metadata:
  name: daily8-dev-db-owner
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: daily8_user
  password: CHANGE_ME_TO_A_STRONG_PASSWORD
