apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny-ingress.yml
  - allow-daily8-backend-to-postgres.yml
  - allow-daily8-backend-to-redis.yml
  - allow-ingress-nginx-to-daily8-admin.yml
