apiVersion: argoproj.io/v1alpha1
#
kind: Application
metadata:
  name: daily8-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Richpong212/Daily8.git
    targetRevision: dev
    path: k8s/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: daily8-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
