apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: daily8-dev

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/name: daily8
      app.kubernetes.io/environment: dev
      app.kubernetes.io/managed-by: argocd

images:
  - name: daily8-backend-image
    newName: ghcr.io/richpong212/daily8/backend
    newTag: "a5349eb4fa73817626913acec4cc43f7279b67a4"

  - name: daily8-admin-image
    newName: ghcr.io/richpong212/daily8/admin
    newTag: "b7fd52ccb1e7f2d2dc3999d01adee353407a3be1"
